apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: metadig-pg
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:15.6
  bootstrap:
    initdb:
      import:
        type: microservice
        databases:
          - metadig
        source:
          externalCluster: cluster-metadig-10
        pgRestoreExtraOptions:
          - '--verbose'
      database: metadig
      owner: metadig
      secret:
        name: metadig-pg
  storage:
    storageClass: csi-cephfs-sc
    size: 200Gi
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 2
      memory: 4Gi
  externalClusters:
    - name: cluster-metadig-10
      connectionParameters:
        # Use the correct IP or host name for the source database
        host: 10.98.125.147
        user: metadig
        dbname: metadig